- name: configure the Backend
  hosts: BE
  become: yes
  vars:
   login_user : "root"
   login_password: "ExpenseApp@1"
   login_host: 172.31.19.50
  tasks:
  - name: Download the nodejs 20 package
    ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  
  - name: install the nodeje
    ansible.builtin.package:
      name:
       - nodejs
       - unzip
       - mysql-client
       - net-tools
       - python3-pip
       - python3-pymysql
      state: present
  - name: create an user for expense project
    ansible.builtin.user:
      name: expense
      create_home: yes
  - name: create an Directory for application
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download backend code into project Directory
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp
  - name: Unarchive a file 
    ansible.builtin.unarchive:
     src: /tmp/expense-backend-v2.zip
     dest: /app
     remote_src: yes # if you give then only it will check in remote server. otherwise it will check in local machine
  - name: install the npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  
  - name: create the DB and collection in mysql
    #ansible.builtin.command: mysql -h 172.31.34.66 -u root -pExpenseApp@1 < /app/schema/backend.sql
    community.mysql.mysql_db:
      state: import
      name: transactions
      target: /app/schema/backend.sql
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
  - name: Copy the backend file
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/
  - name: start the backend service
    ansible.builtin.systemd_service:
      name: backend
      state: restarted
