- name: Configure the frontend
  hosts: FE
  become: yes
  vars:
    packages:
     - nginx
     - unzip
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
  - name: remove the whole content from nginx directory
    ansible.builtin.command: rm -rf /usr/share/nginx/html/*
  
  - name: remove the default.conf
    ansible.builtin.command: rm -rf /etc/nginx/sites-available/default
  
  - name: Download the frontend code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /var/www/
      remote_src: yes

  - name: copy an nginx config file to nginx default location
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/sites-available/default
  
  - name: restart the nginx
    ansible.builtin.systemd_service:
     name: nginx
     state: restarted
    
  